apitoken: <put your smartthings api token here or set APITOKEN env var>
monitor:
  - temperatureMeasurement
  - illuminanceMeasurement
  - relativeHumidityMeasurement
  - ultravioletIndex
smartthings:
  capabilities:
    - name: switch
      time: wall
period: 10
database:
  type: influxdbv2
  url: http://influxdb:8086
  token: token
  org: org
  bucket: SmartThings
valuemap:
  switch: 
    off: 0
    on: 1